version: 2

run:
  timeout: 3m
  tests: true

issues:
  exclude-dirs:
    - config
    - mocks
    - builder
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
    disable:
      - package-comments
