run:
  timeout: 3m
  tests: true

issues:
  exclude-dirs:
    - config
    - mocks
    - builder
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gofmt
    - goimports
  disable:
    - revive
